### ISSUE TITLE
Incorrect "FR4End" for human J genes IGHJ6*02 & IGHJ6*03

### ISSUE THREAD

**Issue by joltex** [repseqio/library-imgt#5]
The "FR4End" anchor point for human J genes IGHJ6\*02 & IGHJ6\*03 is incorrect resulting in sequences being trimmed by 1 residue too many at the 3' end. The existing value is 61 but should be 62.

**Comment by Davydov-Alex** [comment]
Yes, you are right. But we cannot do anything with it before it will be corrected in the original database (IMGT).

**Comment by Alex-Davydov** [comment]
Yes, you are right. But we cannot do anything with it before it will be corrected in the original database (IMGT).

**Comment by dbolotin** [comment]
@joltex please report this issue directly to IMGT.
